# Generated by Django 2.1.7 on 2019-04-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='students', to='basic_app.School'),
        ),
    ]
